---
name: Ansible Role to Galaxy Publisher
description: Publish a single Ansible role to Galaxy
author: Michael Buluma <bulumaknight@gmail.com>

inputs:
  galaxy_api_key:
    description: Your personal Galaxy key found under Galaxy -> Your Profile -> Preferences -> API Key
    required: true
  git_branch:
    description: The git branch you want to upload.
    required: false
    default: "master"
  path:
    description: The (relative) location of your role.
    required: false
    default: "./"
 
runs:
  using: docker
  image: 'docker://buluma/github-action-galaxy'
  env:
    galaxy_api_key: ${{ inputs.galaxy_api_key }}
    git_branch: ${{ inputs.git_branch }}
    path: ${{ inputs.path }}

branding:
  icon: play  
  color: blue
